// Generated by build/write_buildflag_header.py
// From "base_debugging_flags"
#ifndef BASE_PROTECTED_MEMORY_BUILDFLAGS_H_
#define BASE_PROTECTED_MEMORY_BUILDFLAGS_H_
#include "build/buildflag.h"
#define BUILDFLAG_INTERNAL_USE_LLD() (0)
#endif  // BASE_PROTECTED_MEMORY_BUILDFLAGS_H_
