// Generated by build/write_buildflag_header.py
// From "base_debugging_flags"
#ifndef BASE_CFI_BUILDFLAGS_H_
#define BASE_CFI_BUILDFLAGS_H_
#include "build/buildflag.h"
#define BUILDFLAG_INTERNAL_CFI_ICALL_CHECK() (0)
#endif  // BASE_CFI_BUILDFLAGS_H_
