
#ifndef PARTITION_ALLOC_BUILDFLAGS_H__
#define PARTITION_ALLOC_BUILDFLAGS_H__
#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CAN_UNWIND_WITH_CFI_TABLE() (0)  
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() (0)

#endif  // PARTITION_ALLOC_BUILDFLAGS_H__
