// Generated by build/write_buildflag_header.py
// From "base_debugging_flags"
#ifndef sanitizer_buildflags_h__
#define sanitizer_buildflags_h__
#include "build/buildflag.h"
#define ADDRESS_SANITIZER

#define BUILDFLAG_INTERNAL_IS_HWASAN (1)

#endif  // BASE_DEBUG_DEBUGGING_FLAGS_H_


